from flask import render_template,Flask,request,Response
from prometheus_client import Counter,generate_latest
from flipkart.data_ingestion import DataIngestor
from rag_chain import RAGChainBuilder

from dotenv import load_dotenv

load_dotenv()

REQUEST_COUNT = Counter("http_requests_total" , "Total HTTP Request") # this is custom metrics function call. it keeps incrementing for each execution of app

def create_app():

    app = Flask(__name__)
    
    vector_store = DataIngestor().ingest(load_existing=True) # from DataIngestor class in data_ingestion.py in flipkart folder call function ingest()
    rag_chain = RAGChainBuilder(vector_store).build_chain() # from RAGChainBuilder class in rag_chain.py call function build_chain()

    @app.route("/") # home page route
    def index():
        REQUEST_COUNT.inc() # each time the homepage is running , this call is incremented
        return render_template("index.html") # loading the UI page, even if no input or and process is done, just display
    
    @app.route("/get" , methods=["POST"]) # route point , when the functionality or process starts, that is when user starts typing and entering that input by clicking the send button
    def get_response():

        user_input = request.form["msg"] # the user input pattern defined in index.html, name = "msg"

# RAG chain response, crate a nested dictionary to fetch the user-session and previous chat history
        response = rag_chain.invoke(
            {"input" : user_input},
            config={"configurable" : {"session_id" : "user-session"}}
        )["answer"]   # actual answer value stored in a variable response

        return response
    
    @app.route("/metrics")  # endpoint to check metrics
    def metrics():
        return Response(generate_latest(), mimetype="text/plain") # default metrics generated by prometheus, in-build + custom metrics as mention above in REQUEST_COUNT
    
    return app      # returns the app

if __name__=="__main__":
    app = create_app()
    app.run(host="0.0.0.0",port=5000,debug=True) # production IP address 0.0.0.0, anywhere